# Generated by Django 5.1.7 on 2026-01-03 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_organization'),
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='transport_mode',
            field=models.CharField(choices=[('car', 'Car'), ('bike', 'Bike'), ('auto', 'Auto Rickshaw'), ('public', 'Public Transport'), ('any', 'Any Mode')], default='car', max_length=20),
        ),
        migrations.AddField(
            model_name='trip',
            name='trip_type',
            field=models.CharField(choices=[('offering', 'Offering Ride'), ('seeking', 'Seeking Ride')], default='offering', max_length=20),
        ),
        migrations.AlterField(
            model_name='trip',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='authentication.vehicle'),
        ),
    ]
