# Generated by Django 5.1.7 on 2026-01-03 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversionRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('rate', models.DecimalField(decimal_places=4, max_digits=10)),
                ('description', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'conversion_rates',
            },
        ),
        migrations.CreateModel(
            name='NGOPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('focus_area', models.CharField(max_length=100)),
                ('website', models.URLField()),
                ('verified', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('total_donations_received', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('trees_planted', models.IntegerField(default=0)),
                ('co2_offset_kg', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ngo_partners',
            },
        ),
        migrations.CreateModel(
            name='RedemptionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('DISCOUNT', 'Discount Coupon'), ('VOUCHER', 'Gift Voucher'), ('PRODUCT', 'Physical Product'), ('SERVICE', 'Service Benefit')], max_length=20)),
                ('diamond_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('partner_name', models.CharField(max_length=200)),
                ('partner_logo', models.URLField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('terms_conditions', models.TextField()),
                ('validity_days', models.IntegerField(default=90)),
                ('stock_available', models.IntegerField(default=100)),
                ('active', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'redemption_options',
                'ordering': ['diamond_cost'],
            },
        ),
        migrations.CreateModel(
            name='DiamondWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('lifetime_earned', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('lifetime_redeemed', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diamond_wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'diamond_wallets',
            },
        ),
        migrations.CreateModel(
            name='DiamondTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('EARN_RIDE', 'Earned from Ride'), ('EARN_DONATION', 'Earned from Donation'), ('EARN_REFERRAL', 'Earned from Referral'), ('EARN_BONUS', 'Bonus Reward'), ('REDEEM_DISCOUNT', 'Redeemed for Discount'), ('REDEEM_VOUCHER', 'Redeemed for Voucher'), ('REDEEM_PRODUCT', 'Redeemed for Product')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('co2_saved', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('description', models.TextField()),
                ('reference_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='rewards.diamondwallet')),
            ],
            options={
                'db_table': 'diamond_transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('diamonds_earned', models.DecimalField(decimal_places=2, max_digits=10)),
                ('co2_equivalent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_id', models.CharField(max_length=100)),
                ('status', models.CharField(default='completed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to=settings.AUTH_USER_MODEL)),
                ('ngo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='rewards.ngopartner')),
            ],
            options={
                'db_table': 'donations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Redemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diamonds_spent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('voucher_code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('redeemed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to=settings.AUTH_USER_MODEL)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='rewards.redemptionoption')),
            ],
            options={
                'db_table': 'redemptions',
                'ordering': ['-created_at'],
            },
        ),
    ]
