# Generated by Django 5.1.7 on 2026-01-03 16:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Messages auto-delete after 24 hours', null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='behavior_rating',
            field=models.IntegerField(default=5, help_text='1-5: How was their behavior?'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='cleanliness_rating',
            field=models.IntegerField(default=5, help_text='1-5: How clean/hygienic?'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='communication_rating',
            field=models.IntegerField(default=5, help_text='1-5: Communication quality'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='punctuality_rating',
            field=models.IntegerField(default=5, help_text='1-5: Was the person on time?'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='would_ride_again',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterUniqueTogether(
            name='feedback',
            unique_together={('ride', 'from_user', 'to_user')},
        ),
    ]
